### ISSUE TITLE
Discord notification do not seem to be working

### ISSUE THREAD

**Issue by SebNYD** [daghaian/nzbthrottle#5]
Hello,

First, thanks a lot for this tool, I have been using it for a while and it's very useful :)

I just tried to use Discord notifications but it doesn't seem to work, I'm getting the following error :
`-NotifyDiscord: WARNING : Failed to send Discord notification: Bad Request - Unsupported Parameters. (error=400).`

Does it work for you ?

Thanks

**Comment by daghaian** [comment]
Hi @SebNYD, I can certainly take a look and see if anything stands out.

**Comment by daghaian** [comment]
@SebNYD  I"ve updated the notification library dependency to the latest and it looks like it works now.  I've pushed a new docker image as well. Please let me know if anything comes up.

**Comment by SebNYD** [comment]
> @SebNYD I"ve updated the notification library dependency to the latest and it looks like it works now. I've pushed a new docker image as well. Please let me know if anything comes up.

Hello,

Sorry for the delayed answer but it doesn't seem to have fixed the issue on my side.
I'm getting the same error in logs.

Thanks anyway,

**Comment by daghaian** [comment]
@SebNYD Did you make sure you pulled the docker image again? Ill check again but it was working for my local test.

**Comment by SebNYD** [comment]
Yes I did :)

**Comment by daghaian** [comment]
@SebNYD  I apologize, there was an issue when building the original docker image. Please try now, I'm pretty sure your issue will no longer occur.

**Comment by SebNYD** [comment]
Indeed, it's now working smoothly :)

Thanks a lot.
